### ISSUE TITLE
Some breaking changes

### ISSUE THREAD

**Issue by VeselaHouba** [Mickaelh51/ar_heplify#2]
Hi @Mickaelh51 , I've created fork of your nice work, switched to molecule testing instead of vagrant and did some other changes. I don't want to send changes as PR, because it would possibly break stuff for existing users. So this is just "FYI" and feel free to re-use anything from https://github.com/VeselaHouba/ansible-role-heplify if interested.

**Comment by Mickaelh51** [comment]
Hi,
thanks a lot for your email.
I don't use molecule. For my information, what are the advantages of
Molecule rather than Vagrant ?

++

Le lun. 9 nov. 2020 à 10:34, Jan Michalek <notifications@github.com> a
écrit :

**Comment by VeselaHouba** [comment]
Molecule is a whole framework designed for testing ansible roles, it tests e.g.
- lint & best-practices
- install role
- idempotency
- run custom after-install tests
So you don't need to write everything by yourself. Molecule can use Vagrant as hosts provider, so it's not exactly replacement, but more likely a wrapper. Other hosts providers are docker, aws cloud, ...

**Comment by Mickaelh51** [comment]
thanks a lot !
I'm going to test it ;)
have a good day

Le lun. 9 nov. 2020 à 11:00, Jan Michalek <notifications@github.com> a
écrit :

**Comment by VeselaHouba** [comment]
Cleaning old open issues -> closing.
